### ISSUE TITLE
Why "private: true"

### ISSUE THREAD

**Issue by sarendipitee** [evs-chris/ractive-autocomplete#2]
I would love to use this in my project, but my only option right now is to make a fork, edit the package.json and publish it myself. If you don't want to maintain it on NPM, that's fine, but at least have a proper package.json with a `main`.

Seems odd to use NPM for your dep management but then not add the component to the registry.

**Comment by evs-chris** [comment]
I tried npm for front-end dependency management a while back and it just didn't feel right to me. This happened to be around the time npmjs.org was having availability issues, so I also got a little burned. Anyways...

I'd be happy to set up the package manifest to have it more usable from npm. Would adding a main element for use with a github ref be sufficient?

**Comment by sarendipitee** [comment]
Yes, if the package.json was in the `build` branch because that's where the non-es6 version is as well...So you'd need two different package.json's or scrap the `build` branch in favor of a `dist` folder like how Rich does it in a lot of his repos. :|

**Comment by evs-chris** [comment]
I finally got 'round to fixing a few issues with this component and have published 0.4.0 with the package manifest in the right place for use with npm. I've confirmed you can reference it with `git://github.com/evs-chris/ractive-autocomplete#0.4.0`. Sorry it took so long.

**Comment by sarendipitee** [comment]
Cool! Thanks
